//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVANADE.MODULOS.Modulos.AVANADE_ESTOQUE.Resourcers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FornecedorResourcer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FornecedorResourcer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVANADE.MODULOS.Modulos.AVANADE_ESTOQUE.Resourcers.FornecedorResourcer", typeof(FornecedorResourcer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CPNJ está invalido, o formato deve ser XX.XXX.XXX/XXXX-XX..
        /// </summary>
        public static string CNPJInvalido {
            get {
                return ResourceManager.GetString("CNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe cadastro para o CNPJ informado..
        /// </summary>
        public static string CnpjJaCadastrado {
            get {
                return ResourceManager.GetString("CnpjJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo CNPJ é obrigatório..
        /// </summary>
        public static string CNPJObrigatorio {
            get {
                return ResourceManager.GetString("CNPJObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo e-mail inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome contato obrigatório..
        /// </summary>
        public static string NomeContatoObrigatorio {
            get {
                return ResourceManager.GetString("NomeContatoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome fantasia é obrigatório..
        /// </summary>
        public static string NomeFantasiaObrigatorio {
            get {
                return ResourceManager.GetString("NomeFantasiaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome é obrigatório..
        /// </summary>
        public static string RazaoSocialObrigatorio {
            get {
                return ResourceManager.GetString("RazaoSocialObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo telefone inválido, o formato deve ser (DD) 9 9999-9999..
        /// </summary>
        public static string TelefoneInvalido {
            get {
                return ResourceManager.GetString("TelefoneInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo telefone é obrigatório..
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
    }
}
