//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVANADE.MODULOS.Modulos.AVANADE_ESTOQUE.Resourcers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProdutoResourcer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProdutoResourcer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVANADE.MODULOS.Modulos.AVANADE_ESTOQUE.Resourcers.ProdutoResourcer", typeof(ProdutoResourcer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo categoria é obrigatório..
        /// </summary>
        public static string CategoriaObrigatorio {
            get {
                return ResourceManager.GetString("CategoriaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto com código único {0}  já cadastrado.
        /// </summary>
        public static string CodigoUnicoJaCadastrado {
            get {
                return ResourceManager.GetString("CodigoUnicoJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo código único é obrigatório..
        /// </summary>
        public static string CodigoUnicoObrigatorio {
            get {
                return ResourceManager.GetString("CodigoUnicoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo descrição é obrigatório..
        /// </summary>
        public static string DescricaoObrigatorio {
            get {
                return ResourceManager.GetString("DescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo esta ativo é obrigatório..
        /// </summary>
        public static string EstaAtivoObrigatorio {
            get {
                return ResourceManager.GetString("EstaAtivoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo está em promoção é obrigatório..
        /// </summary>
        public static string EstaEmPromocaoObrigatorio {
            get {
                return ResourceManager.GetString("EstaEmPromocaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor não existe, ou está desativado..
        /// </summary>
        public static string FornecedorInvalido {
            get {
                return ResourceManager.GetString("FornecedorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo fornecedor  é obrigatório..
        /// </summary>
        public static string FornecedorObrigatorio {
            get {
                return ResourceManager.GetString("FornecedorObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca não existe, ou está desativada..
        /// </summary>
        public static string MarcaInvalida {
            get {
                return ResourceManager.GetString("MarcaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo marca é obrigatório..
        /// </summary>
        public static string MarcaObrigatorio {
            get {
                return ResourceManager.GetString("MarcaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo preço é obrigatório, e não pode ser menor ou igual a zero..
        /// </summary>
        public static string PrecoObrigatorio {
            get {
                return ResourceManager.GetString("PrecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo quantidade em estoque é obrigatório e não pode ser menor ou igual a zero..
        /// </summary>
        public static string QuantidadeEstoqueObrigatorio {
            get {
                return ResourceManager.GetString("QuantidadeEstoqueObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo tem frete grátis é obrigatório..
        /// </summary>
        public static string TemFreteGratisObrigatorio {
            get {
                return ResourceManager.GetString("TemFreteGratisObrigatorio", resourceCulture);
            }
        }
    }
}
